# Generated by Django 3.2.4 on 2021-06-18 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
